# Generated by Django 4.2.9 on 2024-01-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_deadline', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('max_team_students', models.IntegerField()),
                ('min_team_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('submission_deadline', models.DateField()),
                ('ending_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_members', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.battle')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(related_name='students', to='CKBApp.team')),
                ('tournaments', models.ManyToManyField(related_name='students', to='CKBApp.tournament')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battles_managed', models.ManyToManyField(related_name='educators', to='CKBApp.battle')),
                ('tournaments', models.ManyToManyField(related_name='educators', to='CKBApp.tournament')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.tournament'),
        ),
    ]
