# Generated by Django 4.2.9 on 2024-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='battles_managed',
            field=models.ManyToManyField(blank=True, related_name='educators', to='CKBApp.battle'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='educators', to='CKBApp.tournament'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='students', to='CKBApp.team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='students', to='CKBApp.tournament'),
        ),
    ]
