# Generated by Django 4.2.9 on 2024-01-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0002_alter_educator_battles_managed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CKBApp.team')),
                ('user_invited', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites_received', to='CKBApp.user')),
                ('user_who_invite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites_sent', to='CKBApp.user')),
            ],
        ),
    ]
