# Generated by Django 4.2.9 on 2024-01-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0005_alter_invite_user_invited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='user_invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites_received', to='CKBApp.user'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_who_invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites_sent', to='CKBApp.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='CKBApp.user'),
        ),
    ]
