# Generated by Django 4.2.9 on 2024-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0006_alter_invite_user_invited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='code_kata',
            field=models.FileField(null=True, upload_to='codes_kata/'),
        ),
    ]
