# Generated by Django 4.2.9 on 2024-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0012_remove_battle_code_kata'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='code_kata',
            field=models.FileField(default=None, upload_to='codes_kata/'),
        ),
    ]
