# Generated by Django 4.2.9 on 2024-02-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0013_battle_code_kata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='code_kata',
        ),
    ]
