# Generated by Django 4.2.9 on 2024-02-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0014_remove_battle_code_kata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.team'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to='CKBApp.user'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_who_invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to='CKBApp.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='CKBApp.user'),
        ),
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.student')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBattleRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.battle')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBattleRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.battle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.student')),
            ],
        ),
    ]
