# Generated by Django 4.2.9 on 2024-02-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0015_alter_invite_team_alter_invite_user_invited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbattleranking',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.battle'),
        ),
        migrations.AlterField(
            model_name='teambattleranking',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.battle'),
        ),
        migrations.AlterField(
            model_name='teambattleranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.team'),
        ),
        migrations.AlterField(
            model_name='tournamentranking',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.tournament'),
        ),
    ]
