# Generated by Django 4.2.9 on 2024-02-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0016_alter_studentbattleranking_battle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.battle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKBApp.student')),
            ],
        ),
    ]
