# Generated by Django 4.2.9 on 2024-02-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0017_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='manually_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
