# Generated by Django 4.2.9 on 2024-02-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CKBApp', '0019_battle_code_kata'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='repository_created',
            field=models.BooleanField(default=False),
        ),
    ]
